# -*- coding: utf-8 -*-
"""prime.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tP8LuUn-nvXMvTBPoGXRNxLXS8LPY6V6
"""
# B반 4조 김수진 prime 과제

def check_prime(num):
    divisor=[]
    for i in range(2,num):
        if num % i == 0:
            divisor.append(i)
    
    return divisor==[]
    
def main():
    a=13
    b=15
    if check_prime(a):
        print(str(a)+'는 소수입니다.')
    else:
        print(str(a)+'는 소수가 아닙니다.')

    if check_prime(b):
        print(str(b)+'는 소수입니다.')
    else:
        print(str(b)+'는 소수가 아닙니다.')